version: '3.8'

services:

  # Mailhog
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge