version: "3.8"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge
