version: "3.8"

services:

  # Docker app
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex_app
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge