version: "3.8"

services:
  # Docker db
  mariadb:
    image: mariadb:latest
    container_name: glpi_db
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - app_network

  #Docker app
  glpi:
    image: diouxx/glpi
    container_name : glpi_app
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/www/html
    environment:
      - TIMEZONE=Europe/Paris
    networks:
      - app_network


# Docker Networks
networks:
  app_network:
    driver: bridge