version: "3.8"

services:
  # Docker App
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./docker.sock:/var/run/docker.sock
    networks:
      - app_network

# docker Networks
networks:
  app_network:
    driver: bridge