version: "3.8"

services:

  # Docker app
  vaultarden_app:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge