version: '3.8'

services:

  # Docker Database
  wikijs_db:
    image: postgres:11-alpine
    container_name: wikijs_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: $WIKI_POSTGRES_DATABASE
      POSTGRES_PASSWORD: $WIKI_POSTGRES_PASSWORD
      POSTGRES_USER: $WIKI_POSTGRES_USER
    logging:
      driver: "none"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - app_network

  # Docker app
  wiki_app:
    image: ghcr.io/requarks/wiki:2
    restart: unless-stopped
    container_name: wikijs_app
    environment:
      DB_PORT: $WIKI_POSTGRES_PORT
      DB_TYPE: $WIKI_DB_TYPE
      DB_HOST: $WIKI_DB_HOST
      DB_USER: $WIKI_POSTGRES_USER
      DB_PASS: $WIKI_POSTGRES_PASSWORD
      DB_NAME: $WIKI_POSTGRES_DATABASE
    depends_on:
      - wikijs_db
    volumes:
      - ./sideload:/wiki/data/sideload
      - ./config.yml:/wiki/config.yml
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge