version: '3.8'

services:

  # Postgres Service
  postgres:
    image: postgres:16-alpine
    container_name: postgres_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./storage-db:/var/lib/postgresql/data
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge